version: '3'

services:
  omr-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    env_file:
      - .env
    restart: unless-stopped
